alias lynx='lynx -accept_all_cookies'
alias clr='clear'
alias ff='firefox'
alias battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "state|to\ full|percentage"'
alias config='/usr/bin/git --git-dir=/home/ajpkim/dotfiles/ --work-tree=/home/ajpkim'
