alias dotfiles='/usr/bin/git --git-dir=/home/ajpkim/.dotfiles --work-tree=$HOME'
alias ff='firefox'
alias clr='clear'
alias bat='cat /sys/class/power_supply/BAT0/capacity'
alias e='emacs'
alias ef='emacs -fs'
alias et='emacs -nw'
alias xcc='xclip -selection clipboard'